workspace = { members = [ "advance-trait", "all-patterns", "arr",
  "borrow",
  "complex-num",
  "composite", "enum-type", "flow-control",
  "function", "generic", "match-if-let", "method",
  "number", "option",
  "other-type",
  "own", "pattern-match",
  "statement",
  "struct-memory", "trait-object", "trait-study",
  "variables", "vector-study",
] }
[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
